### ISSUE TITLE
Implement contact us functionality 

### ISSUE THREAD

**Issue by bridget75** [Jaspero/pronaikon#3]
![image](https://user-images.githubusercontent.com/93909566/172563786-ef9da02f-578a-4898-97ea-a1d8011e1d15.png)

**Comment by flauc** [comment]
ajmo samo pojednostaviti polja na: 

Ime,
Kontakt,
Poruka

**Comment by flauc** [comment]
@Ktarnaj this is connected on `contact-form.component.ts`
